# Generated by Django 4.0.6 on 2022-07-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='DepartmentsId',
            new_name='DepartmentId',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='DepartmentsName',
            new_name='DepartmentName',
        ),
    ]
