# Generated by Django 4.0.6 on 2022-07-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_rename_departmentsid_departments_departmentid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='EmployeesId',
            new_name='EmployeeId',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='EmployeesName',
            new_name='EmployeeName',
        ),
    ]
